os: osx

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  # python requirements needed to create distribution
  - "python -m pip install wheel"
  - "python -m pip install cython"
  # get latest version of all submodules (gorilla audio)
  - "git submodule update --init --recursive"

script:
  - "cmake gorilla-audio/build
  - "cmake --build . --config Release"
  - "python setup.py build"
  - "python setup.py bdist_wheel"
