environment:
  global:
    DISTRIBUTIONS: "bdist_wheel"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 10"

    - PYTHON: "C:\\Python33"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 10"


    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 10"

    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 14"

# x64 builds disabled because libvorbis lacks such support
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_ARCH: 64
#      MSVC_VERSION: "Visual Studio 10 Win64"
#
#
#    - PYTHON: "C:\\Python33-x64"
#      PYTHON_ARCH: 64
#      MSVC_VERSION: "Visual Studio 10 Win64"
#      DISTUTILS_USE_SDK: "1"
#
#    - PYTHON: "C:\\Python34-x64"
#      DISTUTILS_USE_SDK: "1"
#      MSVC_VERSION: "Visual Studio 10 Win64"
#      PYTHON_ARCH: 64
#
#    - PYTHON: "C:\\Python35-x64"
#      MSVC_VERSION: "Visual Studio 14 Win64"
#      PYTHON_ARCH: 64

init:
  - "ECHO %PYTHON% %PYTHON_ARCH% %MSVC_VERSION%"
  - "%PYTHON%\\python.exe --version"

install:
  - set
  # python requirements needed to create distribution
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install cython"
  # get latest version of all submodules (gorilla audio)
  - "git submodule update --init --recursive"

build: off

build_script:
   # build gorilla audio that will be later statically linked
  - "cmake -G \"%MSVC_VERSION%\" gorilla-audio/build -DCMAKE_TOOLCHAIN_FILE=appveyor.%PYTHON_ARCH%.toolchain.cmake -DENABLE_OPENAL:STRING=0 -DENABLE_XAUDIO2:STRING=1 -DENABLE_DIRECTSOUND:STRING=0 -DDIRECTXSDK_PATH=\"%DXSDK_DIR%\""
  - "cmake --build . --config Release"
  # build our sdist and wheel distribution
  - "build.cmd %PYTHON%/python setup.py build"
  - "build.cmd %PYTHON%/python setup.py %DISTRIBUTIONS%"

artifacts:
  - path: dist\*
  - path: gorilla-audio\bin\**\*
