environment:
#  global:
#    DISTUTILS_USE_SDK: "1"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: "32"
      DISTRIBUTIONS: "sdist"

init:
  - "ECHO %PYTHON% %PYTHON_ARCH%"
  - "%PYTHON%\\python.exe --version"

install:
  - set
  # python requirements needed to create distribution
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install cython"
  - "%PYTHON%\\python.exe -m pip install pypandoc"
  # get latest version of all submodules (gorilla audio)
  - "git submodule update --init --recursive"

build: off

build_script:
   # build gorilla audio that will be later statically linked
  - "cmake -G \"Visual Studio 10\" gorilla-audio/build -DCMAKE_TOOLCHAIN_FILE=appveyor.%PYTHON_ARCH%.toolchain.cmake -DENABLE_OPENAL:STRING=0 -DENABLE_XAUDIO2:STRING=1 -DENABLE_DIRECTSOUND:STRING=0 -DDIRECTXSDK_PATH=\"%DXSDK_DIR%\""
  - "cmake --build . --config Release"
  # build our sdist and wheel distribution
  - "build.cmd %PYTHON%/python setup.py build"
  - "build.cmd %PYTHON%/python setup.py %DISTRIBUTIONS%"

artifacts:
  - path: dist\*
  - path: gorilla-audio\bin\**\*
