FROM quay.io/pypa/manylinux1_i686:latest

MAINTAINER Michał Jaworski <swistakm@gmail.com>

WORKDIR /opt/

# CMake installation
RUN curl -O https://cmake.org/files/v3.6/cmake-3.6.2.tar.gz && \
    tar -xvf cmake-3.6.2.tar.gz

WORKDIR /opt/cmake-3.6.2

RUN ./bootstrap
RUN make
RUN make install

# Force 32 bit address mode emulation so yum during builds knows it is targeted
# for x86 arch.
RUN linux32 yum install openal-devel -y && yum clean all -y
